language: ruby
cache: bundler
rvm:
  - 2.6

before_install: gem update --system
install: src/scripts/bootstrap
script: src/scripts/cibuild

env:
  matrix:
    - JEKYLL_VERSION="~> 3.8.0"
#    - JEKYLL_VERSION=">= 4.0.0.pre.alpha1"
