language: ruby
cache:
  bundler: true,
  npm: true,
  directories:
    - src/node_modules
rvm:
  - 2.6

before_install:
  - gem update --system
  - nvm install ${NODE_VERSION} --lts=erbium --latest-npm
install: src/scripts/bootstrap
script: src/scripts/cibuild

env:
  jobs:
    - JEKYLL_VERSION="~> 3.8.0"
    - NODE_VERSION="12.18.0"
    #    - JEKYLL_VERSION=">= 4.0.0.pre.alpha1"
