#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml

# Accepts connections on port 4000 from any source
host: 0.0.0.0
port: 4000

url: 'http://localhost:4000'
baseurl: ''
urlimg: 'http://localhost:4000/images/'

# See › https://github.com/jekyll/jekyll-gist#disabling-noscript-support
gist:
  noscript: false

# Disable when not in production
google_analytics_tracking_id: false
fb_app_id: false
