en:
  - menu_name: "Services"

  - name: "Contact"
    url: "/contact/"
    title: "Contact"

  - name: "RSS"
    url: "/feed.xml"
    title: "Subscribe to RSS Feed"

  - name: "Atom"
    url: "/atom.xml"
    title: "Subscribe to Atom Feed"

  - name: "sitemap.xml"
    url: "/sitemap.xml"
    title: "Sitemap for Google Webmaster Tools"

bg:
  - menu_name: "Услуги"

  - name: "Контакти"
    url: "/bg/contact/"
    title: "Контакти"

  - name: "RSS"
    url: "/feed.xml"
    title: "Subscribe to RSS Feed"

  - name: "Atom"
    url: "/atom.xml"
    title: "Subscribe to Atom Feed"

  - name: "sitemap.xml"
    url: "/sitemap.xml"
    title: "Sitemap for Google Webmaster Tools"