#!/bin/sh

set -e

echo "ES linting..."
(cd src && npm run lint)

echo "Testing..."
(cd src && npm run test)

echo "Bundling..."
(cd src && npm run bundle)

echo "Building the site..."
bundle exec jekyll build
